<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUpUFEXO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUpUFEXO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUpUFEXO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUpUFEXO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUpUFEXO\App_KernelDevDebugContainer([
    'container.build_hash' => 'UpUFEXO',
    'container.build_id' => '0ae8522d',
    'container.build_time' => 1672756725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUpUFEXO');
