<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container625xrc5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container625xrc5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container625xrc5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container625xrc5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container625xrc5\App_KernelDevDebugContainer([
    'container.build_hash' => '625xrc5',
    'container.build_id' => '44633be9',
    'container.build_time' => 1673271050,
], __DIR__.\DIRECTORY_SEPARATOR.'Container625xrc5');
