<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIVOe7eH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIVOe7eH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIVOe7eH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIVOe7eH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIVOe7eH\App_KernelDevDebugContainer([
    'container.build_hash' => 'IVOe7eH',
    'container.build_id' => '01196b0a',
    'container.build_time' => 1672753180,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIVOe7eH');
